server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.226.130:3306/schema1
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
  application:
    name: mybank