server:
  port: 8001
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yejingtao/forblog
          search-paths: /config
          username: username
          password: password
  application:
    name: config-server
  rabbitmq:
    host: 192.168.226.130
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/

management:
  security:
    enabled: false