server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.226.130:3306/schema1
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: mybank
logging:
  file: ./spring-boot.log
  level:
    org.springframework.web: DEBUG
    com.myback.dao: DEBUG